#!/bin/bash
echo '[-] syncing mattijs.korpershoek@gmail.com'
cd ~/linux-data/.email/mattijs.korpershoek.gmail/ && gmi sync
echo '[-] syncing mkorpershoek@redhat.com'
cd ~/linux-data/.email/mkorpers.redhat.com/ && gmi sync
# echo "[-] disabled gmi sync via notmuch"
