#!/bin/bash
echo "[-] Syncing mattijs.korpershoek@gmail.com ..."
cd ~/.email/mattijs.korpershoek.gmail/ && gmi sync
echo "[-] Syncing mkorpershoek@redhat.com ..."
cd ~/.email/mkorpers.redhat.com/ && gmi sync
