(spacemacs/declare-prefix "aa" "Android")
(when (configuration-layer/package-used-p 'log-tools)
  (spacemacs/set-leader-keys "aal" 'log-tools))
(when (configuration-layer/package-used-p 'device-control)
  (spacemacs/set-leader-keys "aad" 'device-control))
