
[window]
decorations = "None"
padding = { x = 0, y = 0}
dynamic_padding = true
option_as_alt = "None"

[font]
size = 10.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/themes/zenburn.toml"
]
